###############################################################################
# Dummy - Kbuild
#
#
###############################################################################

apps-$(CONFIG_APP_DUMMY) += dummy

dummy-y = common libsel4 libmuslc libsel4muslcsys libsel4simple-default \
          libsel4vka libsel4allocman libsel4simple libutils \
          libsel4utils libsel4debug libsel4vspace \
          libplatsupport libsel4platsupport libcpio libelf \
          libprocess libthread libinit libmmap libsel4sync liblockwrapper

#dummy-components-y += 
dummy-components = $(addprefix $(STAGE_BASE)/bin/, $(dummy-components-y))

dummy: export COMPONENTS=${dummy-components}
dummy: ${dummy-components-y} $(dummy-y)
