###############################################################################
# Test Process - Kbuild
#
#
###############################################################################

apps-$(CONFIG_APP_TEST_PROC) += test_proc

test_proc-y = common libsel4 libmuslc libsel4muslcsys libsel4simple-default \
              libsel4vka libsel4allocman libsel4simple libutils \
              libsel4utils libsel4debug libsel4vspace \
              libplatsupport libsel4platsupport libcpio libelf \
              libprocess libthread libinit libmmap libsel4sync liblockwrapper

#test_proc-components-y += 
test_proc-components = $(addprefix $(STAGE_BASE)/bin/, $(test_proc-components-y))

test_proc: export COMPONENTS=${test_proc-components}
test_proc: ${test_proc-components-y} $(test_proc-y)
