###############################################################################
# liballocate - Kbuild
#
#
###############################################################################

libs-$(CONFIG_LIB_ALLOCATE) += liballocate
liballocate: libsel4 common $(libc)

