###############################################################################
# Root Task - Kbuild
#
#
###############################################################################

apps-$(CONFIG_APP_ROOT_TASK) += root_task

root_task-y = common libsel4 libmuslc libsel4muslcsys libsel4simple \
              libsel4vka libsel4allocman libsel4platsupport libutils \
              libsel4simple-default libsel4utils libsel4debug libsel4vspace \
              libelf libcpio \
              libprocess libthread libinit libmmap libsel4sync liblockwrapper

root_task-components-y += child_example dummy
root_task-components = $(addprefix $(STAGE_BASE)/bin/, $(root_task-components-y))

root_task: export COMPONENTS=${root_task-components}
root_task: ${root_task-components-y} kernel_elf $(root_task-y)
