###############################################################################
# libmmap - Kbuild
#
#
###############################################################################

libs-$(CONFIG_LIB_MMAP) += libmmap
libmmap: libsel4 common $(libc) libsel4vka libsel4allocman libplatsupport libsel4platsupport \
           libsel4simple libsel4vspace \
           libsel4sync liblockvka libinit

