###############################################################################
# liblockvka - Kbuild
#
#
###############################################################################

libs-$(CONFIG_LIB_LOCKVKA) += liblockvka 
liblockvka: libsel4 common $(libc) libsel4vka libsel4allocman libsel4sync

