###############################################################################
# Child Example - Kbuild
#
#
###############################################################################

apps-$(CONFIG_APP_CHILD_EXAMPLE) += child_example

child_example-y = common libsel4 libmuslc libsel4muslcsys \
                  libsel4vka libsel4allocman libutils \
                  libsel4utils libsel4debug libsel4vspace \
                  libplatsupport libsel4platsupport \
                  libprocess libthread libsync libinit

child_example: $(child_example-y)
